Repository red-recursion-teamdev/git-workshop, pull requests merged in 2022-09, with the labels that each got.

#3 htmlファイルの基本フォーマットの作成
  index.html
Labels: low

#5 Bootstrapを用いたNavバー作成
  index.html
Labels: 新規開発, low

#7 add slider and footer
  images/cake-gd64323ee6_1920.jpg
  images/coffee-g0f61b9559_1920.jpg
  images/pancakes-ge010170d1_1920.jpg
  index.html
Labels: 新規開発

#9 スライダー以降の部分のコンテンツ追加
  .DS_Store
  images/cake-4910417_1280.jpg
  images/coffee-6632524_1280.jpg
  index.html
  styles.css
Labels: 新規開発

#11 HTML要素の微調整とレスポンシブデザインの適用
  index.html
  styles.css
Labels: 新規開発
